# Generated by Django 3.1.5 on 2022-05-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='complain_type',
        ),
    ]
