# Generated by Django 3.1.5 on 2022-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
