# Generated by Django 3.1.5 on 2022-06-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_jobs_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
