# Generated by Django 3.1.5 on 2022-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220618_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('X', 'X'), ('M', 'M'), ('XL', 'XL')], max_length=50)),
                ('color', models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK')], max_length=50)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
