# Generated by Django 3.1.5 on 2022-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
